# Generated by Django 3.1.2 on 2020-10-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201021_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='u_phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
