# Generated by Django 3.1.2 on 2020-10-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201021_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('Food', 'Food'), ('Home Made', 'Home Made'), ('Laundry', 'Laundry'), ('Grocery', 'Grocery'), ('Dessert', 'Dessert')], max_length=200, null=True),
        ),
    ]
