# Generated by Django 3.1.2 on 2020-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201028_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='locality',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
