# Generated by Django 3.1.2 on 2020-12-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seller_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[('Food', 'Food'), ('Home Made', 'Home Made'), ('Laundry', 'Laundry'), ('Grocery', 'Grocery'), ('Dessert', 'Dessert'), ('Art', 'Art'), ('Craft', 'Craft')], max_length=200, null=True),
        ),
    ]
