# Generated by Django 3.1.2 on 2020-12-10 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201210_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='t_id',
        ),
    ]
