# Generated by Django 3.1.2 on 2020-12-12 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20201211_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dno',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pincode',
            field=models.IntegerField(blank=True),
        ),
    ]
